---
- name: Copy a file to multiple hosts
  hosts: all
  become: yes
  tasks:
    - name: Copy a file to remote hosts
      copy:
        src: /path/to/local/file.txt
        dest: /path/to/remote/destination/file.txt
        owner: root
        group: root
        mode: '0644'


