- name: Install packages on remote hosts
  hosts: all
  become: yes
  tasks:
    - name: Install multiple packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - nginx
        - vim

