- name: Install packages on remote hosts
  hosts: all
  become: yes
  tasks:
    - name: Install multiple packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - vim


